# Generated by Django 2.2 on 2019-04-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_count', '0002_readdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='readdetail',
            name='comment_num',
            field=models.IntegerField(default=0, verbose_name='评论数量'),
        ),
    ]
