# Generated by Django 2.2 on 2019-04-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_count', '0004_auto_20190429_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readdetail',
            options={'ordering': ['-hot_num']},
        ),
        migrations.AlterModelOptions(
            name='readnum',
            options={'ordering': ['-read_num']},
        ),
        migrations.AlterField(
            model_name='readdetail',
            name='hot_num',
            field=models.IntegerField(default=0, verbose_name='热度'),
        ),
    ]
